---

- name: "{{user}}"
  shell: "echo {{user}}"

- name: "clone {{onprem_labs}}"
  git:
    repo: "https://github.com/gpe-mw-training/{{onprem_labs}}.git"
    dest: "{{lab_home_dir}}/{{onprem_labs}}"
    update: yes
  become: yes
  become_user: "{{user}}"

- name: Build {{onprem_labs}}
  shell: "{{mvn_install_dir}}/{{mvn_root}}/bin/mvn clean package -DskipTests"
  args:
    chdir: "{{lab_home_dir}}/{{onprem_labs}}/services"
  become: yes
  become_user: "{{user}}"

- name: Clean {{onprem_labs}}
  shell: "{{mvn_install_dir}}/{{mvn_root}}/bin/mvn clean"
  args:
    chdir: "{{lab_home_dir}}/{{onprem_labs}}/services"
  become: yes
  become_user: "{{user}}"


