- hosts: fuse_messaging
  remote_user: root
  vars_prompt:
    - name: is_ravello
      prompt: "Is this a VM that will be managed by GPTE CloudForms (y/n)? "
      default: "y"
      private: no

  roles:
    - hostname
    - update
    - tools
    - docker

#   - epel                      # centos only
    - geerlingguy.repo-epel     # rhel; need to execute the following beforehand:  sudo ansible-galaxy install geerlingguy.repo-epel

    - qpid_tools
    - yum-clean
    - reboot
    - guest-additions
    - useradd
    - mate
    - selinux
    - firewalld
    - java
    - maven
    - amq-repos
#   - oc                        # Red Hat JBoss FIS only
    - yum-clean
    - amq
    - rhn_unsubscribe
