- hosts: fuse_messaging
  remote_user: jboss
  become: yes
  become_user: root
  become_method: sudo
  vars_prompt:
    - name: is_ravello
      prompt: "Is this a VM that will be managed by GPTE CloudForms (y/n)? "
      default: "y"
      private: no

  roles:
    - hostname
    - maven
