:scrollbar:
:data-uri:

= Ansible playbook for virtual machines that support GPTE _fuse_*_ courses

== Base image

. The following base virtual machine should already be running.
+
Ansible will then customize this virtual machine.

* OS : RHEL 7 x68_64
** RHEL is needed (instead of CENTOS) because latest supported `qpid-dispatch` libraries only come from supported RHEL channels
+
Ensure the following channels are enabled

*** rhel-7-server-rpms
*** rhel-7-server-extras-rpm
*** rhel-7-server-supplementary-rpm
*** a-mq-interconnect-1-for-rhel-7-server-rpms
*** a-mq-clients-1-for-rhel-7-server-rpms

* Disk: 20GB, dynamically allocated, VDI format
* Memory : 2GB
* Base images installation:
** Hostname: rhtamq
** Network: on
** HDD Partitioning:
*** File system : ext4
*** boot 500 MiB, swap 2048 MiB, root partition 17.5 GiB
** Minimal installation
** No user created
** Root password : jb0ssredhat!
* Post-installation tasks:
** copy public ssh key to virtual machine for user root

. It is highly recommended that this virtual machine be in a `qcow2` image format.
+
`qcow2` can then be transformed to VDI if/when need be.


== Pre-reqs

. Ensure the target RHEL OS has already been registered with Red Hat Network using _subscription_manager_.
. Execute the following from your local environment:
+
-----
sudo ansible-galaxy install geerlingguy.repo-epel
-----

== Inventory file
Copy the `hosts.example` file to `hosts`, and replace `<ip address of virtual machine>` with the IP address of the virtual machine.

== Installation Artifacts

. `amq-repos/files`:
.. jboss-amq7-7.0.0.ER15-1-maven-repository.zip
.. jboss-amq-qpid-jms-0.20.0.redhat-2-maven-repository.zip

== Provisioning
In this directory, execute the following command:

-----
$ ansible-playbook -i hosts fuse_messaging.yml
-----

== Linux only sparsify and transform image

Disregard these sections if not using a linux distro as your host environment.

=== Sparsify qcow2 image

Sparsifying a virtual machine can make a dramatic reduction in the size of the virtual machine image.

. Ensure that target VM to be sparsified has been cleaned of all temporary work files.
+
Also, execute: `yum clean all`

. Shutdown the virtual machine.

. if /tmp/ (on local workstation) does not have enough space, set the `TMPDIR` environment variable to a directory path that does have sufficient space.
+
Example as follows:
+
-----
export TMPDIR=/u02/vm/
-----

. sparsify the image.  Example as follows:
+
-----
virt-sparsify --compress ose_dev.qcow2 ose_dev_sparse.qcow2
-----

=== Conversion to VDI

-----
qemu-img convert -O vdi fuse_messaging_ga-1.0.qcow2 fuse_messaging_ga-1.0.vdi
-----
