---

- name: Add jboss user
  user: name={{user}} groups=wheel password={{password}}

- name: Ensure /opt directory is owned by {{user}}:{{user}}
  file: 
    path: "/opt"
    state: directory 
    owner: "{{user}}"
    group: "{{user}}"

