---

- name: Set environment variables and aliases for all users
  blockinfile:
    dest: /etc/bashrc
    block: |

        # Git Completion: RHEL 7
        source /usr/share/git-core/contrib/completion/git-prompt.sh
        GIT_COMPLETION_PATH="/etc/bash_completion.d/git"
        if [ -f "$GIT_COMPLETION_PATH" ]; then
            GIT_PS1_SHOWDIRTYSTATE=true
            . "$GIT_COMPLETION_PATH"
            ADD_PS1='$(__git_ps1)'
        fi

        if [[ ${EUID} == 0 ]] ; then
            PS1="\[\033[01;31m\]\h\[\033[01;34m\] \w\[\033[33m\]$ADD_PS1\[\033[34m\] \$\[\033[00m\] "
        else
            PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[33m\]$ADD_PS1\[\033[34m\] \$\[\033[00m\] "
        fi

- name: Add jboss user
  user: name={{user}} groups=wheel password={{password}}

- name: Ensure /opt directory is owned by {{user}}:{{user}}
  file: 
    path: "/opt"
    state: directory 
    owner: "{{user}}"
    group: "{{user}}"

