---

- name: "{{user}}"
  shell: "echo {{user}}"

- name: "clone {{onprem_labs}}"
  git:
    repo: "https://github.com/gpe-mw-training/{{onprem_labs}}.git"
    dest: "{{lab_home_dir}}/{{onprem_labs}}"
    update: yes
  become: yes
  become_user: "{{user}}"
- name: chown of {{onprem_labs}}
  file:
    path: "{{lab_home_dir}}/{{onprem_labs}}"
    owner: "{{user}}"
    group: "{{user}}"
