- hosts: appdev_microservices_development
  remote_user: root
  
  roles:
    - update
    - useradd
    - selinux
    - tools
    - reboot
    - mate
    - java
    - maven
    - jq
    - oc-cli
    - jbds
    - yum-clean
    - rhn_unsubscribe

