- hosts: centos-vm
  remote_user: root

  roles:
    - update
    - yum-clean
    - reboot
    - epel
    - guest-additions
    - useradd
    - mate
    - selinux
    - tools
    - zerofree
    - java
    - mariadb
    - mariadb-bpms-schema
    - maven
    - maven-repo
    - bpms
    - bpms-ddl
    - bpms-quartz
    - yum-clean
    - ssl-ca
    - ldif
