---

- name: Create installation target directory
  file: path={{jxplorer_install_dir}} state=directory owner={{user}} group={{user}}

- name: Unzip JXplorer archive
  unarchive: src={{jxplorer_distro}} dest={{jxplorer_install_dir}}
  become: yes
  become_user: "{{user}}"

- name: Set file permissions
  file: 
    path={{jxplorer_home}}/{{item}}
    mode=0775
  with_items:
    - jxplorer.sh

- name: Copy start script
  template: src={{item}} dest={{lab_home_dir}}
  with_items:
    - start-jxplorer.sh

- name: Set file owner and permissions
  file: path={{lab_home_dir}}/{{item}} owner={{user}} group={{user}} mode=0775
  with_items: 
    - start-jxplorer.sh