---

# This appears to be unreliable ... frequent, non-deterministic timeouts.
# # Better to ensure these channels are enabled in: /etc/yum/repos.d/redhat.repo
# - name: Enable base rhel channel
#   shell: "subscription-manager repos --enable={{rhel_channel}} "

#- name: Update all packages
#  yum: name=* state=latest
#  register: updatepackages

- name: Install deltarpm
  yum: name=deltarpm state=present

- name: Update all RHEL packages
  shell: yum -y update --skip-broken
  register: updatepackages
