---

- name: Install docker
  yum: 
    name: docker,device-mapper-libs,device-mapper-event-libs
    state: present

- name: bounce docker
  command: systemctl enable docker.service
- command: systemctl restart docker.service
