---

- name: Copy oc binary
  copy: src={{oc_distro}} dest={{oc_install_dir}} owner={{user}} group={{user}}

- name: Set file permissions
  file:
    path={{oc_install_dir}}/{{item}}
    mode=0775
  with_items:
    - oc
