---

- name: Install firewalld
  yum: 
    name: firewalld 
    state: present

- name: bounce firewalld
  command: systemctl enable firewalld.service
  command: systemctl restart firewalld.service

- firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 9990/tcp
    permanent: true
    state: enabled

- name: bounce firewalld
  command: systemctl restart firewalld.service
