---

# This appears to be unreliable ... frequent, non-deterministic timeouts.
# Better to enuse these channels are neabled in: /etv/yum.repos.di/redhat.repo
# - name: Enable Extras and Optional channels
# shell: "subscription-manager repos --enable={{extras_channel}} --enable={{supplementary_channel}} --enable={{optional_channel}}"

- name: Install tools (ensure that Extras repo is enabled since it containers docker).
  yum: name=git,zip,bzip2,unzip,gettext,wget,curl,telnet,tree state=present

# libaio package comes included in a minimal install of CENTOS
# It is a dependency of the following package : device-mapper-persistent-data
# device-mapper-persistent-data  is not needed for the purpose of fuse courses
#
# We want to intentionally remove libaio so that students of fuse_messaging_7 intially observe behavior of their broker when it is not installed.
# Afterwards, they will be instructed to manually install
#
# Turns out can't delete libaio without also deleting docker (used as part of qpid-dispatch labs)
#- name: Delete libaio
#  yum: name=libaio state=removed

# https://github.com/apache/qpid-dispatch/blob/master/doc/book/console_installation.adoc
#- name: Install python-websockify  
#  yum: name=python-websockify state=present
