---

- name: clone oc-cluster-wrapper project to /opt directory
  git:
    repo: https://github.com/openshift-evangelists/oc-cluster-wrapper.git
    dest: /opt/oc-cluster-wrapper
    update: yes
  become: yes
  become_user: "{{user}}"

- name: create link to oc-cluster executable
  file:
    src: /opt/oc-cluster-wrapper/oc-cluster
    dest: /usr/bin/oc-cluster
    state: link
