:scrollbar:
:data-uri:

== Ansible playbook for Red Hat Americas Technical Exchange - Process Driven Applications

=== Base image

* OS : CentOS 7 x68_64
* Disk: 20GB, dynamically allocated, VDI format
* Memory : 4GB
* Base images installation:
** Hostname: bpms
** Network: on
** HDD Partitioning:
*** File system : ext4
*** boot 500 MiB, swap 2048 MiB, root partition 17.5 GiB
** Minimal CentOS installation
** No user created
** Root password : jb0ssredhat!
* Post-installation tasks:
** copy public ssh key to virtual machine for user root

=== Binary files

The following binary files must be added to the playbook, to the `files` directory of the role:

* Role `bpms` :
** `jboss-bpmsuite-6.4.0.GA-deployable-eap7.x.zip`
** `jboss-eap-7.0.0.zip`
* Role `rhsso` :
** `rh-sso-7.0.0.zip`
* Role `rhsso-adapter` :
** `rh-sso-7.0.0-eap7-adapter.zip`
* Role `maven`
** `apache-maven-3.2.5-bin.zip`
* Role `oc`
** `oc version 3.2.0.44`
* Role `jxplorer`
** `jxplorer-3.3.1.2-project.zip`

=== Maven repository

The `maven-repo` role seeds the Maven repository on the virtual machine by copying the contents of `files/repository` to `/home/jboss/.m2/repository` on the virtual machine.

The `files/repository` directory is initially empty. It can be manually populated with `rsync` from a virtual machine instance on which the labs have been executed. We are working on a mechanism to have it automatically populated.

=== Inventory file

Copy the `hosts.example` file to `hosts`, and replace `<ip address of virtual machine>` with the IP address of the virtual machine.

=== Provisioning

In the `ansible` directory, issue the following command:

----
$ ansible-playbook -i hosts bpms.yml
----

=== Virtual machine compacting

The `zerofree` tool allows to compact the virtual machine disk size by reclaiming storage of deleted files. +
The virtual machine has the `zerofree` tool in the `/usr/bin` directory.

For a how-to: http://www.thelinuxdaily.com/2010/02/shrinking-a-dynamic-virtualbox-disk-image/

==== zero free alternative

For VMs based on XFS, an alternative to the use of _zerofree_ is:  http://www.netreliant.com/news/8/17/Compacting-VirtualBox-Disk-Images-Linux-Guests.html
