---

- name: Add jboss user
  user: name={{user}} groups=wheel password={{password}}

- name: Ensure /opt directory is owned by {{user}}:{{user}}
  file: 
    path: "/opt"
    state: directory 
    owner: "{{user}}"
    group: "{{user}}"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Create {{user}} operating system user with ability to control docker
  user: name={{user}} groups=wheel,docker password={{password}}
